version: "3.9"

services:
  app:
    build: .
    ports:
      - "3001:3000"

    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - PORT=3000

    depends_on:
      - db

    networks:
      - pinovx-net

  db:
    image: postgres:15

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    ports:
      - "5432:5432"

    networks:
      - pinovx-net

networks:
  pinovx-net: